spring.application.name=lumberlake
logging.level.sun.rmi.transport.tcp=ERROR
bucket.batch-size=12
bucket.resource-pattern=classpath*:static/img/photobook/*
bucket.public-path=/img/photobook/
bucket.alt-text=Jack Russell Terrier van Lumberlake kennel
